# Generated by Django 6.0.7 on 2026-07-29 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='classroom',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, to='main.classroom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='grade',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='main.grade'),
            preserve_default=False,
        ),
    ]
