# Generated by Django 6.0.7 on 2026-07-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_book_uploaded_at_alter_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='previews/'),
        ),
    ]
