# Generated by Django 6.0.7 on 2026-07-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_book_preview_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='preview_image',
        ),
        migrations.AddField(
            model_name='book',
            name='preview_pdf',
            field=models.FileField(blank=True, upload_to='jpgs/'),
        ),
    ]
