# Generated by Django 6.0.7 on 2026-07-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_book_preview_image_book_preview_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='preview_pdf',
        ),
        migrations.AddField(
            model_name='book',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='jpgs/'),
        ),
    ]
