# Generated by Django 6.0.7 on 2026-07-27 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Author',
            new_name='author',
        ),
    ]
