# Generated by Django 6.0.7 on 2026-07-27 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_book_author_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
    ]
