# Generated by Django 6.0.7 on 2026-07-31 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_student_user'),
        ('main', '0009_remove_book_user'),
    ]

    operations = [
    ]
